/*
 * Params.h
 *
 *  Created on: May 12, 2018
 *      Author: kevin
 */

#ifndef MISSION7_STATE_ESTIMATOR_INCLUDE_MISSION7_STATE_ESTIMATOR_PARAMS_H_
#define MISSION7_STATE_ESTIMATOR_INCLUDE_MISSION7_STATE_ESTIMATOR_PARAMS_H_


#define RATE 50


#endif /* MISSION7_STATE_ESTIMATOR_INCLUDE_MISSION7_STATE_ESTIMATOR_PARAMS_H_ */
